#!/bin/sh

tmux -S /tmp/pair.socket has-session -t pair
if [[ $? == 1 ]] ; then
  tmux -S /tmp/pair.socket new-session -d -s pair -n Vim
  tmux -S /tmp/pair.socket select-window -t pair:Vim
fi
tmux -S /tmp/pair.socket -2 attach -t pair

